#! /usr/bin/env python

import sys

from quiz import Quiz

if __name__ == "__main__":
  wordFile = sys.argv[1]
  quiz = Quiz()
  quiz.add_translations(wordFile)
  quiz.start()
  for q in quiz:
      q.query()
